sudo: required
dist: xenial
language: python
python: 3.7
services:
  - docker
branches:
  only:
  - master
env:
  global:
    - COMMIT=$(echo $TRAVIS_COMMIT | grep -o '^...')
  matrix:
    - CONTEXT=.build/latest.tar.gz TAG=latest
    - CONTEXT=.build/alpine3.9.tar.gz TAG=alpine3.9
    - CONTEXT=.build/python.tar.gz TAG=python
    - CONTEXT=.build/python-3.7.tar.gz TAG=python-3.7
    - CONTEXT=.build/python-3.7-alpine3.9.tar.gz TAG=python-3.7-alpine3.9
    - CONTEXT=.build/python-3.6.tar.gz TAG=python-3.6
    - CONTEXT=.build/python-3.6-alpine3.9.tar.gz TAG=python-3.6-alpine3.9
    - CONTEXT=.build/php-cli.tar.gz TAG=php-cli
    - CONTEXT=.build/php-cli-7.3.tar.gz TAG=php-cli-7.3
    - CONTEXT=.build/php-cli-7.3-alpine3.9.tar.gz TAG=php-cli-7.3-alpine3.9
    - CONTEXT=.build/php-fpm.tar.gz TAG=php-fpm
    - CONTEXT=.build/php-fpm-7.3.tar.gz TAG=php-fpm-7.3
    - CONTEXT=.build/php-fpm-7.3-alpine3.9.tar.gz TAG=php-fpm-7.3-alpine3.9
    - CONTEXT=.build/node-6.17.tar.gz TAG=node-6.17
    - CONTEXT=.build/node-6.17-alpine3.9.tar.gz TAG=node-6.17-alpine3.9
    - CONTEXT=.build/node-8.16.tar.gz TAG=node-8.16
    - CONTEXT=.build/node-8.16-alpine3.9.tar.gz TAG=node-8.16-alpine3.9
    - CONTEXT=.build/docker-18.09.tar.gz TAG=docker-18.09
    - CONTEXT=.build/docker-18.09-alpine3.9.tar.gz TAG=docker-18.09-alpine3.9
install:
  - echo $COMMIT
  - pip install pyyaml &>/dev/null
  - python -m unittest discover tests
  - ./make.py

script:
  - docker build -t kudato/baseimage:$TAG - < $CONTEXT
  - docker tag kudato/baseimage:$TAG kudato/baseimage:$TAG-$COMMIT
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push kudato/baseimage:$TAG
  - docker push kudato/baseimage:$TAG-$COMMIT
